//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionSolicitudes
    {
        public int IdRecepcion { get; set; }
        public int IDSolicitud { get; set; }
        public Nullable<int> IDEncargado { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public int IdEstado { get; set; }
    
        public virtual EstadoSolicitud EstadoSolicitud { get; set; }
        public virtual SolicitudCredito SolicitudCredito { get; set; }
    }
}
