//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public int IdTipoCambio { get; set; }
        public string Moneda { get; set; }
        public decimal Compra { get; set; }
        public decimal Venta { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int IdEncargado { get; set; }
    
        public virtual Encargados Encargados { get; set; }
    }
}
